name: Send Azkar Notifications

on:
  schedule:
    # فحص كل 5 دقائق
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Firebase Admin
        run: npm install firebase-admin@13.6.0

      - name: Check and send notification
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FCM_TOKEN: ${{ secrets.FCM_TOKEN }}
        run: node send-notification.js
