name: Send Azkar Notifications

on:
  schedule:
    # 06:00 بتوقيت الجزائر (UTC+1)
    - cron: "5 5 * * *"

    # 17:00 بتوقيت الجزائر (UTC+1)
    - cron: "5 16 * * *"

  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Send notification
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FCM_TOKEN: ${{ secrets.FCM_TOKEN }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-service-account.json
          node send-notification.js
